version: '3.4'

services:
  docker.api:
    image: ${DOCKER_REGISTRY-}dockerapi
    build:
      context: .
      dockerfile: docker.api/Dockerfile
    depends_on:
        - "mssql-server"

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
